title:			Annie Hsieh
tagline:		Blog - Annie Hsieh
url:        http://www.anniehsieh.com
author:
  name:       "Annie Hsieh"
  email:      "Some musings about web development, Ruby on Rails, my career, and tech"
markdown: 	rdiscount
permalink:	pretty
highlighter:    pygments
paginate: 	5
